# permissions for end users to view caches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cache-viewer-role
rules:
- apiGroups:
  - infinispan.infinispan.org
  resources:
  - caches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infinispan.infinispan.org
  resources:
  - caches/status
  verbs:
  - get
