# permissions for end users to view infinispans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infinispan-viewer-role
rules:
- apiGroups:
  - infinispan.infinispan.org
  resources:
  - infinispans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infinispan.infinispan.org
  resources:
  - infinispans/status
  verbs:
  - get
