apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
config:
  sourceType: ConfigMap
  sourceRef:  infinispan-app-configuration
  name: cloud-ephemeral.xml
  secret: cluster-secrets
spec:
  size: 3
