apiVersion: v1
kind: Secret
metadata:
  name: connect-secret
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: developer
      password: changeme
    - username: operator
      password: changemetoo
